server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          mybooks-client-oidc:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://127.0.0.1:8080/login/code/mybooks-client-oidc"
            scope: openid
            client-name: mybooks-client-oidc
        provider:
          spring:
            issuer-uri: http://auth-server:9000