spring:
  config:
    activate:
      on-profile: dev

app:
  environment: development

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: prod

app:
  environment: production

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: test

app:
  environment: testing

server:
  port: 8081